### ISSUE TITLE
Are there any plans to release TensorFlow v1.x checkpoints (.ckpt, .meta, .index)?

### ISSUE THREAD

**Issue by PINTO0309** [AISIN-TRC/E2Pose#4]
Hello, Author.

Thank you for publishing this wonderful model. I am amazed at how well this model performs.

https://user-images.githubusercontent.com/33194443/205527406-94bb9549-5c37-44c1-9fcb-eb66420e9d07.mp4

Also, using the `frozen_model.pb` you have made available, I have generated an optimized ONNX and made it available in my model zoo, citing the GPLv2 license.
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/333_E2Pose

It is my understanding that this model is optimized and trained for `[N,512,512,3]` input resolutions, but I would like to generate optimized models for other resolutions if possible. I would be very happy to make use of this model, especially in the field of HCI research.

Therefore, I would be very happy if you plan to publish the `checkpoints` generated by TensorFlow v1.x. Because I have the skills to transform the `checkpoints (.ckpt, .meta, .index)` on my own to optimize the ONNX.  I would like to generate my own Protocl Buffers file with input resolution redefined as [N,H,W,3] and use it in my research.

If you are not very interested, please ignore this issue.
Sorry to bother you.

**Comment by PINTO0309** [comment]
I understood that variable resolution checkpoint's are very difficult. The accuracy and speed at close range with a resolution of 512x512 is very good, so I am withdrawing this issue.

I will try to train the model on my own to generate checkpoints of different resolutions when I need to do so.

Thank you very much.

**Comment by MasakazuTobeta** [comment]
Thank you for your interest in E2Pose.

As you understand, the current model cannot support flexible resolution input.
However, we have trained models that include a variety of fixed resolution inputs.
We will publish these in soon, so please be patient.

**Comment by PINTO0309** [comment]
Thank you! I am looking forward to it.

**Comment by PINTO0309** [comment]
I have optimized all the models you additionally committed with post-processed ONNX and committed them to my repository along with the demo code. :smile_cat: 
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/333_E2Pose
